export const userData = {
    githubUser: "shakeelansari63",
    devUsername: "shakeelansari63",
    github: "https://github.com/shakeelansari63",
    facebook: "https://www.facebook.com/shakeelansari63/",
    linkedIn: "https://www.linkedin.com/in/shakeelansari63/",
    twitter: "https://twitter.com/shakeelansari63",
    stackOverflow: "https://stackoverflow.com/users/8178487/shakeel-ansari",
    leetcode: "https://leetcode.com/shakeelansari63/",
    badges: "https://credly.com/users/shakeelansari63",
    skills: [
        "Data Engineering",
        "SQL",
        "Python",
        "Spark",
        "Teradata",
        "ML",
        "Azure Synapse",
        "Hadoop",
        "Airflow",
        "Docker",
        "Kubernetes",
        "Azure",
    ],
    timezone: "+5.5",
    expo: [
        {
            name: "NSE-Chatbot",
            description: "Chatbot for NSE related info.",
            appUrl: "https://nse-chatbot.azurewebsites.net/",
            codeUrl: "https://github.com/shakeelansari63/NSE-Chatbot",
            thumbnail: "",
        },
        {
            name: "Poke-Budgy",
            description: "Budget Planner in your pocket.",
            appUrl: "https://play.google.com/store/apps/details?id=com.shakeelansari63.pokebudgy",
            codeUrl: "https://github.com/shakeelansari63/poke-budgy",
            thumbnail: "",
        },
        {
            name: "MyTrA",
            description:
                "My True Assistant. AI assistant for your mobile with power of MCP and Agents.",
            appUrl: "",
            codeUrl: "https://github.com/shakeelansari63/MyTrA",
            thumbnail: "",
        },
        {
            name: "Rocket-Invo",
            description: "Billing software for small scale business.",
            appUrl: "",
            codeUrl: "https://github.com/shakeelansari63/Rocket-Invo",
            thumbnail: "",
        },
        {
            name: "SQLyser",
            description: "Analyse your SQL Queries.",
            appUrl: "",
            codeUrl: "https://github.com/shakeelansari63/sqlyser",
            thumbnail: "",
        },
        {
            name: "ShakeelAnsari.Me",
            description:
                "Personal Portfolio App. Website written in PHP and React for Personal Portfolio showcase.",
            appUrl: "https://shakeelansari.me/",
            codeUrl: "https://github.com/shakeelansari63/ShakeelAnsari.Me",
            thumbnail: "",
        },
    ],
};
